version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - wget -cO - https://github.com/kevinswiber/postmanctl/releases/download/v1.1.3/postmanctl_1.1.3_Linux_x86_64.tar.gz > ./postmanctl.tar.gz
      - tar -xzf ./postmanctl.tar.gz postmanctl && mv ./postmanctl /usr/local/bin/postmanctl
      - "echo \"contexts:\n  build:\n    apikey: $POSTMAN_API_KEY\n    apiroot: https://api.postman.com\n\" > ~/.postmanctl.yaml"
      - postmanctl config use-context build
      - wget -cO - https://github.com/stedolan/jq/releases/download/jq-1.4/jq-linux-x86_64 > /usr/local/bin/jq
      - npm install openapi-to-postmanv2@1.1.17 -g

  build:
    commands:
      - echo "Building..." # Run build sequence here...
  post_build:
    commands:
      - ./scripts/update-postman-api.sh
      - ./scripts/sync-postman-collection.sh

