version: 0.2

phases:
  install:
    commands:
      - wget -cO - https://github.com/kevinswiber/postmanctl/releases/download/v1.1.2/postmanctl_1.1.2_Linux_x86_64.tar.gz > ./postmanctl.tar.gz
      - tar -xzf ./postmanctl.tar.gz /usr/local/bin/postmanctl
      - "echo \"contexts:\n  build:\n    apikey: $POSTMAN_API_KEY\n    apiroot: https://api.postman.com\n\" > ~/.postmanctl.yaml"
      - postmanctl config use-context build

  build: # Run build sequence here...
  post_build:
    commands:
      - ./scripts/sync-postman-collection.sh

